name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -e .[dev]

    - name: Build package
      run: python -m build

    - name: Check install
      run: pip install dist/*.whl

    - name: Test CLI
      run: |
        view-psql --help | grep Usage

